# numpy

In [1]:
import numpy as np

In [3]:
np.random,uniform(5)


NameError: name 'uniform' is not defined

In [4]:
print(np.random.choice([2,3,4],20,replace=True))

[3 2 4 3 4 3 4 4 4 3 2 3 3 4 4 2 2 3 3 3]


In [9]:
np.repeat([1,2],3)

array([1, 1, 1, 2, 2, 2])

In [10]:
np.r_[1:3:3j]

array([ 1.,  2.,  3.])

In [11]:
np.c_[1:6:3j, [7,8,9]]

array([[ 1. ,  7. ],
       [ 3.5,  8. ],
       [ 6. ,  9. ]])

# wekytoryzacja

In [8]:
np.r_[1,2,4]+np.r_[10,20,30]

array([11, 22, 34])

In [ ]:
## Broadcasting, s. 110 Uzgadanianie kształtów

In [13]:
## Wbudowane operacje na wektorach

In [40]:
x=np.r_[1,4,6]
y=np.r_[3,3,7]
np. minimum(x,y)

array([1, 3, 6])

In [38]:
x<=y

array([ True, False,  True], dtype=bool)

In [21]:
np.eye(3,4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

In [23]:
1 !=np. eye(3,4)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True]], dtype=bool)

In [25]:
x>2

array([False,  True,  True], dtype=bool)

In [27]:
x<5

array([ True,  True, False], dtype=bool)

In [46]:
(x>2) & (x<5)


array([False,  True, False], dtype=bool)

In [52]:
np.array([[1, 2, 3], [4, 5, 6]], np.int32)

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [45]:
A.mean(axis=0) # 0 wiersze - zapadanie się macierzy - tego wymiary nie ma być w wyniku

NameError: name 'A' is not defined

In [57]:
 x[::-1] #odwracanie elementów

array([6, 4, 1])

In [59]:
x[::2]=99

In [62]:
x[x>90]

array([99, 99])